name: cnn_jigsaw_solver
channels:
  - defaults
  - conda-forge
dependencies:
  - aom=3.6.0=hd77b12b_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - dav1d=1.2.1=h2bbff1b_0
  - eigen=3.4.0=h477610d_1
  - expat=2.7.3=h9214b88_0
  - ffmpeg=6.1.1=haa678a1_5
  - filelock=3.20.0=py312haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - fsspec=2025.10.0=py312h4442805_0
  - gflags=2.2.2=he0c23c2_1005
  - giflib=5.2.2=h7edc060_0
  - glog=0.5.0=h4797de2_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py312h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - gst-plugins-base=1.24.12=h91a6125_1
  - gstreamer=1.24.12=hfb93a4f_1
  - gstreamer-orc=0.4.41=h1f81b68_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - importlib-metadata=8.5.0=py312haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jinja2=3.1.6=py312haa95532_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9f=ha349fce_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.1.1=h827c3e9_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libogg=1.3.5=h2466b09_1
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libtheora=1.2.0=habf309d_1
  - libtiff=4.7.0=h404307b_0
  - libtorch=2.5.1=cpu_mkl_h9002858_104
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=h5112557_2
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py312h827c3e9_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h827c3e9_2
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py312haa95532_0
  - mysql-common=9.3.0=h2224204_0
  - mysql-libs=9.3.0=h809f9c2_0
  - networkx=3.5=py312haa95532_0
  - numpy=2.0.1=py312hfd52020_1
  - numpy-base=2.0.1=py312h4dde369_1
  - opencv=4.12.0=py312h6fcf9f4_0
  - openjpeg=2.5.4=h56d5a42_1
  - openssl=3.5.4=h725018a_0
  - opentelemetry-api=1.37.0=py312haa95532_0
  - pcre2=10.46=h5740b90_0
  - pillow=12.0.0=py312ha1fd124_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - python=3.12.12=h716150d_1
  - pytorch=2.5.1=cpu_mkl_py312h0452e45_104
  - qtbase=6.9.2=h06bae2a_4
  - scikit-learn=1.7.2=py312h9296b3f_0
  - scipy=1.16.0=py312h242c13b_0
  - setuptools=80.9.0=py312haa95532_0
  - sleef=3.5.1=h8cc25b3_2
  - sqlite=3.51.0=hda9a48d_0
  - sympy=1.14.0=py312haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - torchvision=0.20.1=cpu_py312h99a9fa7_2
  - typing-extensions=4.15.0=py312haa95532_0
  - typing_extensions=4.15.0=py312haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zipp=3.21.0=py312haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\saada\miniconda3\envs\cnn_jigsaw_solver
